import type { OliviaCrudDefinition, OliviaCrudDomain } from "@/lib/olivia/crud/types";

const string = (maxLength = 2_000, requiredOnCreate = false) => ({
  type: "string" as const,
  maxLength,
  requiredOnCreate,
});
const number = (min = 0, max = Number.MAX_SAFE_INTEGER) => ({ type: "number" as const, min, max });
const boolean = { type: "boolean" as const };
const object = { type: "object" as const };
const array = { type: "array" as const };

export const OLIVIA_CRUD_REGISTRY: Readonly<Record<OliviaCrudDomain, OliviaCrudDefinition>> = {
  client: {
    domain: "client",
    label: "고객",
    identityFields: ["id", "hospitalName"],
    fields: {
      hospitalName: string(200, true),
      contactName: string(120),
      phone: string(40),
      email: string(320),
      specialty: string(160),
      memo: string(5_000),
      originalPhotosLink: string(2_000),
      retouchedPhotosLink: string(2_000),
      totalPaidAmount: number(),
    },
    ownerOnlyFields: ["totalPaidAmount"],
  },
  workflow: {
    domain: "workflow",
    label: "프로젝트/워크플로우",
    identityFields: ["id", "clientName", "projectName"],
    fields: {
      clientId: string(80),
      clientName: string(200, true),
      projectId: string(80),
      projectName: string(240),
      managerName: string(120),
      contactName: string(120),
      contactEmail: string(320),
      shootDate: string(40),
      currentStepKey: { type: "string", enum: ["consult_meeting", "quote", "contract", "conti", "shooting", "payment_confirm", "backup_sorting", "client_selection", "retouching", "final_delivery", "revision", "reward"] },
      nextAction: string(1_000),
      status: { type: "string", enum: ["active", "paused", "completed", "canceled"] },
    },
  },
  memo: {
    domain: "memo",
    label: "메모",
    identityFields: ["id", "title"],
    fields: {
      clientId: string(80),
      hospitalName: string(200),
      title: string(240),
      rawMemo: string(30_000, true),
      summary: string(10_000),
      recommendedPackage: string(500),
      nextAction: string(1_000),
      templateType: { type: "string", enum: ["text", "cornell", "todo", "blank", "grid", "conti"] },
      templateData: object,
    },
  },
  calendar: {
    domain: "calendar",
    label: "일정",
    identityFields: ["id", "title", "date"],
    fields: {
      date: string(20, true),
      title: string(240, true),
      memo: string(10_000),
      category: { type: "string", enum: ["shooting", "client", "admin", "personal", "general"] },
      time: string(10),
      endTime: string(10),
      location: string(500),
      completed: boolean,
    },
  },
  quote: {
    domain: "quote",
    label: "견적서",
    identityFields: ["id", "quoteNumber", "hospitalName"],
    fields: {
      quoteNumber: string(100),
      title: string(240),
      hospitalName: string(200, true),
      contactName: string(120),
      phone: string(40),
      email: string(320),
      quoteDate: string(40),
      shootDate: string(40),
      validUntil: string(40),
      items: array,
      supplyAmount: number(),
      discountAmount: number(),
      vat: number(),
      totalAmount: number(),
      depositAmount: number(),
      balanceAmount: number(),
      depositRate: number(0, 100),
      memos: string(10_000),
      formState: object,
    },
    ownerOnlyFields: ["supplyAmount", "discountAmount", "vat", "totalAmount", "depositAmount", "balanceAmount", "depositRate"],
  },
  contract: {
    domain: "contract",
    label: "계약서",
    identityFields: ["id", "quoteNumber", "hospitalName"],
    fields: {
      quoteNumber: string(100),
      hospitalName: string(200, true),
      contactName: string(120),
      email: string(320),
      quoteData: object,
      signatureDataUrl: string(2_000_000),
    },
    ownerOnlyFields: ["quoteData", "signatureDataUrl"],
  },
  conti: {
    domain: "conti",
    label: "콘티",
    identityFields: ["id", "hospitalName", "title"],
    fields: {
      hospitalName: string(200, true),
      specialties: array,
      title: string(240),
      result: object,
    },
  },
  photo_gallery: {
    domain: "photo_gallery",
    label: "사진 갤러리",
    identityFields: ["id", "hospitalName"],
    fields: {
      hospitalName: string(200, true),
      contactName: string(120),
      contactEmail: string(320),
      shootDate: string(40),
      nasLink: string(2_000, true),
      description: string(10_000),
      clientId: string(80),
      workflowRunId: string(80),
    },
  },
  select_gallery: {
    domain: "select_gallery",
    label: "셀렉 갤러리",
    identityFields: ["id", "title", "hospitalName"],
    fields: {
      title: string(240, true),
      hospitalName: string(200),
      shootingName: string(240),
      shootingDate: string(40),
      clientId: string(80),
      workflowRunId: string(80),
      status: { type: "string", enum: ["draft", "uploading_images", "ready", "mail_draft_created", "mail_sent", "waiting_selection", "selection_submitted", "raw_matching", "raw_matched", "retouching", "completed", "files_expired", "expired"] },
      expireDays: number(1, 30),
      allowWebSelect: boolean,
      allowDownloadUpload: boolean,
      allowDownloadZip: boolean,
      allowResubmit: boolean,
    },
  },
  review: {
    domain: "review",
    label: "후기",
    identityFields: ["id", "clientId", "hospitalName"],
    fields: {
      clientId: string(80),
      hospitalName: string(200),
      overallRating: number(1, 5),
      shootingRating: number(1, 5),
      resultRating: number(1, 5),
      goodPoints: string(10_000),
      improvementPoints: string(10_000),
      publicReviewText: string(20_000),
      allowPublicUse: boolean,
      allowHospitalName: boolean,
      writerName: string(120),
    },
  },
  mail_draft: {
    domain: "mail_draft",
    label: "메일 초안",
    identityFields: ["id", "hospitalName", "subject"],
    fields: {
      type: { type: "string", enum: ["quote", "contract", "conti", "proposal", "original_files", "gallery", "review_form", "monthly_report", "per_report", "per_order", "per_donation", "portal_notification", "select_gallery"] },
      clientId: string(80),
      workflowRunId: string(80),
      hospitalName: string(200, true),
      contactName: string(120),
      toEmail: string(320),
      subject: string(500, true),
      body: string(50_000, true),
      attachments: array,
      links: array,
    },
  },
  agent_task: {
    domain: "agent_task",
    label: "올리비아 업무",
    identityFields: ["id", "title"],
    fields: {
      clientId: string(80),
      projectId: string(80),
      workflowRunId: string(80),
      taskType: string(120),
      title: string(500, true),
      description: string(10_000),
      inputData: object,
      outputData: object,
      priority: { type: "string", enum: ["low", "normal", "high", "urgent"] },
      status: { type: "string", enum: ["pending", "running", "completed", "failed", "waiting_approval", "canceled"] },
    },
  },
};

export function getOliviaCrudDefinition(domain: string) {
  return OLIVIA_CRUD_REGISTRY[domain as OliviaCrudDomain] ?? null;
}

export function getOliviaCrudCapabilities() {
  return Object.values(OLIVIA_CRUD_REGISTRY).map((definition) => ({
    domain: definition.domain,
    label: definition.label,
    operations: ["create", "update"] as const,
    fields: Object.keys(definition.fields),
    ownerOnlyFields: definition.ownerOnlyFields ?? [],
  }));
}
