import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod/v4";
import { runOliviaMcpTool } from "./runTool";

const requestId = z.string().uuid().optional();

export function registerContractTools(server: McpServer) {
  server.registerTool("create_contract", { title: "계약서 생성", description: "Create a contract from the exact active quoteId through Olivia's existing contract tool. Returns contractId; keep using it for this document.", inputSchema: { quoteId: z.string().uuid(), hospitalName: z.string().max(120).optional(), requestId } }, async ({ quoteId, requestId, ...input }) => runOliviaMcpTool("create_contract", "create_contract", { quoteId, ...input }, requestId, { activeWorkspace: "quote", activeResourceId: quoteId }, "mutation"));
  server.registerTool("get_contract", { title: "계약서 조회", description: "Read the canonical Olivia contract by contractId.", inputSchema: { contractId: z.string().uuid(), requestId } }, async ({ contractId, requestId }) => runOliviaMcpTool("get_contract", "get_contract", { contractId }, requestId, { activeWorkspace: "contract", activeResourceId: contractId }));
  server.registerTool("update_contract_terms", { title: "계약 조건 수정", description: "Update contract terms through Olivia and verify stored values. Keep the same contractId across follow-up turns.", inputSchema: { contractId: z.string().uuid(), depositRate: z.number().min(0).max(100).optional(), paymentTerms: z.string().max(2000).optional(), deliveryTerms: z.string().max(2000).optional(), specialTerms: z.string().max(4000).optional(), requestId } }, async ({ contractId, requestId, ...input }) => runOliviaMcpTool("update_contract_terms", "update_contract_terms", input, requestId, { activeWorkspace: "contract", activeResourceId: contractId }, "mutation"));
  server.registerTool("preview_contract", { title: "계약서 미리보기", description: "Return the canonical contract for Desktop/Mobile preview without duplicating it.", inputSchema: { contractId: z.string().uuid(), requestId } }, async ({ contractId, requestId }) => runOliviaMcpTool("preview_contract", "preview_contract", { contractId }, requestId, { activeWorkspace: "contract", activeResourceId: contractId }));
  server.registerTool("request_contract_publish", { title: "계약서 발행 승인 요청", description: "Validate the current contract and prepare an approval request. This does not publish it.", inputSchema: { contractId: z.string().uuid(), requestId } }, async ({ contractId, requestId }) => runOliviaMcpTool("request_contract_publish", "request_contract_publish", {}, requestId, { activeWorkspace: "contract", activeResourceId: contractId }, "approval"));
  server.registerTool("publish_contract", { title: "계약서 최종 발행", description: "Publish the exact contract only after explicit user approval; Olivia validates required terms, signature, linkage, and persisted final status.", inputSchema: { contractId: z.string().uuid(), clientId: z.string().uuid().optional(), workflowRunId: z.string().uuid().optional(), requestId } }, async ({ contractId, clientId, workflowRunId, requestId }) => runOliviaMcpTool("publish_contract", "publish_contract", {}, requestId, { activeWorkspace: "contract", activeResourceId: contractId, activeClientId: clientId, activeProjectId: workflowRunId }, "mutation"));
}
