import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod/v4";
import { runOliviaMcpTool } from "./runTool";

const requestId = z.string().uuid().optional();
export function registerMemoTools(server: McpServer) {
  server.registerTool("memo.create", { title: "메모 생성", description: "Save a consultation memo through Olivia's existing memo API, then read it back and verify the content and linkage. Provide clientId/contextId for linked memos. Set independent=true only when the user explicitly requested an unlinked memo.", inputSchema: { clientId: z.string().uuid().optional(), contextType: z.enum(["client", "project", "schedule", "work"]).optional(), contextId: z.string().uuid().optional(), independent: z.boolean().optional(), title: z.string().max(200).optional(), content: z.string().trim().min(1).max(100000), requestId } }, async ({ requestId, ...input }) => runOliviaMcpTool("memo.create", "memo_create", input, requestId, { activeClientId: input.clientId }, "mutation"));
  server.registerTool("memo.list", { title: "메모 목록", description: "List canonical Olivia memos, optionally scoped to a client/project/schedule/work context.", inputSchema: { contextType: z.enum(["client", "project", "schedule", "work"]).optional(), contextId: z.string().uuid().optional(), requestId } }, async ({ requestId, ...input }) => runOliviaMcpTool("memo.list", "memo_list", input, requestId));
  server.registerTool("memo.search", { title: "메모 검색", description: "Search existing Olivia memo title/content/summary. Use this before choosing among multiple memos.", inputSchema: { query: z.string().trim().min(1).max(200), contextType: z.enum(["client", "project", "schedule", "work"]).optional(), contextId: z.string().uuid().optional(), requestId } }, async ({ requestId, ...input }) => runOliviaMcpTool("memo.search", "memo_search", input, requestId));
  server.registerTool("memo.get", { title: "메모 조회", description: "Read one exact canonical Olivia memo by memoId.", inputSchema: { memoId: z.string().uuid(), requestId } }, async ({ memoId, requestId }) => runOliviaMcpTool("memo.get", "memo_get", { memoId }, requestId, { activeWorkspace: "memo", activeResourceId: memoId }));
  server.registerTool("memo.update", { title: "메모 수정", description: "Update one exact Olivia memo through the existing memo API and verify the saved content.", inputSchema: { memoId: z.string().uuid(), clientId: z.string().uuid().optional(), contextType: z.enum(["client", "project", "schedule", "work"]).optional(), contextId: z.string().uuid().optional(), title: z.string().max(200).optional(), content: z.string().trim().min(1).max(100000), requestId } }, async ({ memoId, requestId, ...input }) => runOliviaMcpTool("memo.update", "memo_update", { memoId, ...input }, requestId, { activeWorkspace: "memo", activeResourceId: memoId, activeClientId: input.clientId }, "mutation"));
}
