import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod/v4";
import { runOliviaMcpTool } from "./runTool";

const requestId = z.string().uuid().optional();
export function registerAnalysisTools(server: McpServer) {
  server.registerTool("trend_analysis.run", { title: "트렌드 분석 실행", description: "Run Olivia's existing trend insight pipeline, persist the canonical trend_insights resource, and verify it as latest.", inputSchema: { industry: z.string().max(120).optional(), requestId } }, async ({ requestId, ...input }) => runOliviaMcpTool("trend_analysis.run", "trend_analysis_run", input, requestId, {}, "mutation"));
  server.registerTool("trend_analysis.get_latest", { title: "최신 트렌드 분석", description: "Read the latest persisted Olivia trend insight for an industry.", inputSchema: { industry: z.string().max(120).optional(), requestId } }, async ({ requestId, ...input }) => runOliviaMcpTool("trend_analysis.get_latest", "trend_analysis_get_latest", input, requestId));
  server.registerTool("trend_analysis.preview", { title: "트렌드 분석 미리보기", description: "Return the latest canonical trend resource for preview without duplicating it.", inputSchema: { industry: z.string().max(120).optional(), requestId } }, async ({ requestId, ...input }) => runOliviaMcpTool("trend_analysis.preview", "trend_analysis_preview", input, requestId));
  server.registerTool("brand_analysis.run", { title: "브랜드 분석 실행", description: "Run Olivia's existing hospital brand diagnosis flow (create, collect, channel analysis, compile), persist it, and verify completed read-back. Requires one confirmed client and at least one channel URL.", inputSchema: { clientId: z.string().uuid().optional(), hospitalName: z.string().max(120).optional(), specialty: z.string().max(120).optional(), websiteUrl: z.string().url().optional(), naverPlaceUrl: z.string().url().optional(), instagramUrl: z.string().url().optional(), requestId } }, async ({ requestId, ...input }) => runOliviaMcpTool("brand_analysis.run", "brand_analysis_run", input, requestId, { activeClientId: input.clientId, activeClientName: input.hospitalName }, "mutation"));
  server.registerTool("brand_analysis.get_latest", { title: "최신 브랜드 분석", description: "Read the latest completed canonical hospital brand diagnosis for one confirmed client.", inputSchema: { clientId: z.string().uuid().optional(), hospitalName: z.string().max(120).optional(), requestId } }, async ({ requestId, ...input }) => runOliviaMcpTool("brand_analysis.get_latest", "brand_analysis_get_latest", input, requestId, { activeClientId: input.clientId, activeClientName: input.hospitalName }));
  server.registerTool("brand_analysis.preview", { title: "브랜드 분석 미리보기", description: "Read one canonical hospital brand diagnosis by resourceId for Desktop/Mobile preview.", inputSchema: { resourceId: z.string().uuid(), requestId } }, async ({ resourceId, requestId }) => runOliviaMcpTool("brand_analysis.preview", "brand_analysis_preview", { resourceId }, requestId, { activeResourceId: resourceId }));
}
