import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod/v4";
import { runOliviaMcpTool } from "./runTool";

const requestId = z.string().uuid().optional();
const sceneFields = z.object({
  name: z.string().max(200).optional(), space_text: z.string().max(300).optional(), minutes: z.number().nonnegative().nullable().optional(),
  keyword: z.string().max(300).optional(), description: z.string().max(4000).optional(), people_text: z.string().max(500).optional(),
  patient_role_text: z.string().max(500).optional(), preparation_text: z.string().max(2000).optional(), note: z.string().max(2000).optional(),
});

export function registerContiTools(server: McpServer) {
  server.registerTool("create_conti", {
    title: "V2 촬영 콘티 생성",
    description: "Create the canonical Desktop V2 conti in conti_runs/groups/scenes through Olivia's existing V2 API. Never creates legacy conti_saves. Confirm one client and provide at least one checked category, staff flag, harmony, or extra item.",
    inputSchema: { clientId: z.string().uuid().optional(), hospitalName: z.string().max(120).optional(), workflowRunId: z.string().uuid().optional(), specialty: z.string().max(120).optional(), doctorCount: z.number().int().min(1).max(10).optional(), staffFlags: z.object({ siljang: z.boolean().optional(), jikwon: z.boolean().optional(), other: z.boolean().optional() }).optional(), harmony: z.boolean().optional(), checked: z.record(z.string(), z.array(z.string())).optional(), extraItems: z.array(z.string().max(200)).max(30).optional(), requestId },
  }, async ({ requestId, ...input }) => runOliviaMcpTool("create_conti", "create_conti_v2", input, requestId, { activeClientId: input.clientId, activeClientName: input.hospitalName, activeProjectId: input.workflowRunId }, "mutation"));
  server.registerTool("get_conti", { title: "V2 콘티 조회", description: "Read the same canonical V2 conti shown by Olivia Desktop.", inputSchema: { contiId: z.string().uuid(), requestId } }, async ({ contiId, requestId }) => runOliviaMcpTool("get_conti", "get_conti_v2", { contiId }, requestId, { activeWorkspace: "conti", activeResourceId: contiId }));
  server.registerTool("update_conti_scene", { title: "V2 콘티 장면 수정", description: "Update one exact canonical V2 scene by sceneId or 1-based position, then read the run back and verify the fields.", inputSchema: { contiId: z.string().uuid(), sceneId: z.string().uuid().optional(), position: z.number().int().min(1).optional(), fields: sceneFields, requestId } }, async ({ contiId, requestId, ...input }) => runOliviaMcpTool("update_conti_scene", "update_conti_scene_v2", { contiId, ...input }, requestId, { activeWorkspace: "conti", activeResourceId: contiId }, "mutation"));
  server.registerTool("add_conti_scene", { title: "V2 콘티 장면 추가", description: "Add a scene to the canonical V2 conti and verify it appears in Desktop data.", inputSchema: { contiId: z.string().uuid(), groupId: z.string().uuid().optional(), fields: sceneFields.optional(), requestId } }, async ({ contiId, requestId, ...input }) => runOliviaMcpTool("add_conti_scene", "add_conti_scene_v2", { contiId, ...input }, requestId, { activeWorkspace: "conti", activeResourceId: contiId }, "mutation"));
  server.registerTool("remove_conti_scene", { title: "V2 콘티 장면 삭제 승인 요청", description: "Resolve one exact scene in the canonical Desktop V2 conti and ask for approval. This never deletes data. Use the returned contiId and sceneId for confirmation.", inputSchema: { contiId: z.string().uuid(), sceneId: z.string().uuid().optional(), position: z.number().int().min(1).optional(), requestId } }, async ({ contiId, requestId, ...input }) => runOliviaMcpTool("remove_conti_scene", "request_remove_conti_scene_v2", { contiId, ...input }, requestId, { activeWorkspace: "conti", activeResourceId: contiId }, "approval"));
  server.registerTool("confirm_remove_conti_scene", { title: "승인된 V2 콘티 장면 삭제", description: "Delete the exact canonical V2 scene only after explicit user approval. Reuse the contiId and sceneId returned by remove_conti_scene; never resolve a different or most-recent scene.", inputSchema: { contiId: z.string().uuid(), sceneId: z.string().uuid(), requestId } }, async ({ contiId, sceneId, requestId }) => runOliviaMcpTool("confirm_remove_conti_scene", "remove_conti_scene_v2", { contiId, sceneId }, requestId, { activeWorkspace: "conti", activeResourceId: contiId }, "mutation"));
  server.registerTool("reorder_conti_scene", { title: "V2 콘티 장면 순서 변경", description: "Move one canonical V2 scene to a 1-based target position and verify the persisted order.", inputSchema: { contiId: z.string().uuid(), sceneId: z.string().uuid().optional(), position: z.number().int().min(1).optional(), targetPosition: z.number().int().min(1), requestId } }, async ({ contiId, requestId, ...input }) => runOliviaMcpTool("reorder_conti_scene", "reorder_conti_scene_v2", { contiId, ...input }, requestId, { activeWorkspace: "conti", activeResourceId: contiId }, "mutation"));
  server.registerTool("get_conti_field_view", { title: "V2 콘티 현장뷰", description: "Return canonical V2 groups/scenes for the same field view used by Desktop.", inputSchema: { contiId: z.string().uuid(), requestId } }, async ({ contiId, requestId }) => runOliviaMcpTool("get_conti_field_view", "get_conti_field_view_v2", { contiId }, requestId, { activeWorkspace: "conti", activeResourceId: contiId }));
  server.registerTool("preview_conti", { title: "V2 콘티 미리보기", description: "Return canonical V2 conti preview data without copying or storing a duplicate.", inputSchema: { contiId: z.string().uuid(), requestId } }, async ({ contiId, requestId }) => runOliviaMcpTool("preview_conti", "preview_conti_v2", { contiId }, requestId, { activeWorkspace: "conti", activeResourceId: contiId }));
}
