import type { MarketingBriefingItem } from "@/lib/dashboardBriefing";

export const FALLBACK_MARKETING_BRIEFING: MarketingBriefingItem[] = [
  {
    id: "fallback-policy-ad-copy",
    category: "policy",
    title: "후기형 의료광고 표현을 다시 점검하세요",
    summary: "치료 효과를 단정하거나 환자 경험을 일반화한 문구가 없는지 고객 채널을 확인할 시점입니다.",
    source: "올리비아 점검 가이드",
    importance: "high",
    recommendation: "기존 블로그와 SNS의 후기형 문구를 우선 점검하세요.",
    actionLabel: "리스크 점검",
    actionHref: "/sns-manager",
  },
  {
    id: "fallback-search-season",
    category: "search_trend",
    title: "계절 진료 키워드 콘텐츠를 준비하세요",
    summary: "계절 변화와 함께 피부·면역·통증 관리 검색 관심이 움직이는 시기입니다.",
    source: "병원 트렌드 분석",
    importance: "medium",
    recommendation: "고객 병원의 주력 진료와 연결되는 계절 콘텐츠를 한 편 기획하세요.",
    actionLabel: "트렌드 보기",
    actionHref: "/trend-dashboard",
  },
  {
    id: "fallback-competitor-profile",
    category: "competitor",
    title: "경쟁 병원의 의료진 소개 방식을 비교하세요",
    summary: "의료진의 전문성과 진료 철학을 사진과 짧은 문장으로 전달하는 구성이 늘고 있습니다.",
    source: "올리비아 경쟁 분석",
    importance: "medium",
    recommendation: "기존 고객 홈페이지의 의료진 소개와 촬영 이미지를 함께 비교하세요.",
    actionLabel: "전략 비교",
    actionHref: "/channel-analyzer",
  },
  {
    id: "fallback-content-process",
    category: "content_insight",
    title: "진료 과정을 보여주는 콘텐츠를 활용하세요",
    summary: "결과만 강조하기보다 상담부터 사후 관리까지의 과정을 보여주면 신뢰 형성에 도움이 됩니다.",
    source: "오늘의 콘텐츠 인사이트",
    importance: "medium",
    recommendation: "촬영 콘티에 상담·설명·관리 장면을 추가해 보세요.",
    actionLabel: "콘텐츠 만들기",
    actionHref: "/sns-manager",
  },
  {
    id: "fallback-market-trust",
    category: "market",
    title: "환자가 확인하고 싶은 신뢰 근거를 정리하세요",
    summary: "의료진 정보, 진료 과정, 공간과 장비를 일관된 이미지로 보여주는 것이 선택에 영향을 줍니다.",
    source: "올리비아 시장 인사이트",
    importance: "low",
    recommendation: "고객별로 부족한 신뢰 이미지를 한 가지씩 정의하세요.",
    actionLabel: "병원 진단",
    actionHref: "/diagnosis",
  },
];
