export type WorkflowStatus = "active" | "paused" | "completed" | "canceled";
export type StepRunStatus = "pending" | "in_progress" | "waiting_approval" | "completed" | "skipped" | "failed";
export type AgentTaskStatus = "pending" | "running" | "completed" | "failed" | "waiting_approval" | "canceled";
export type AgentTaskPriority = "low" | "normal" | "high" | "urgent";
export type ApprovalStatus = "pending" | "approved" | "rejected" | "revision_requested";

export const WORKFLOW_STEPS = [
  {
    key: "consult_meeting",   name: "상담 / 미팅",
    order_index: 1,  requires_approval: false, automation_level: "manual" as const,
    visible_to_client: false, creates_mailing_draft: false, related_feature: "clients",
  },
  {
    key: "quote",             name: "견적서 생성 / 전달",
    order_index: 2,  requires_approval: true,  automation_level: "draft_then_approve" as const,
    visible_to_client: true,  creates_mailing_draft: true,  related_feature: "quotes",
  },
  {
    key: "contract",          name: "계약서 작성 / 전달",
    order_index: 3,  requires_approval: true,  automation_level: "draft_then_approve" as const,
    visible_to_client: true,  creates_mailing_draft: true,  related_feature: "contracts",
  },
  {
    key: "conti",             name: "콘티 작성 / 전달",
    order_index: 4,  requires_approval: true,  automation_level: "draft_then_approve" as const,
    visible_to_client: true,  creates_mailing_draft: true,  related_feature: "conti",
  },
  {
    key: "shooting",          name: "촬영",
    order_index: 5,  requires_approval: false, automation_level: "manual" as const,
    visible_to_client: false, creates_mailing_draft: false, related_feature: "clients",
  },
  {
    key: "backup_sorting",    name: "백업 및 분류",
    order_index: 6,  requires_approval: false, automation_level: "full" as const,
    visible_to_client: false, creates_mailing_draft: false, related_feature: "photo-sorting",
  },
  {
    key: "original_delivery", name: "원본 데이터 전달",
    order_index: 7,  requires_approval: false, automation_level: "full" as const,
    visible_to_client: true,  creates_mailing_draft: false, related_feature: "mailing",
  },
  {
    key: "retouching",        name: "보정",
    order_index: 8,  requires_approval: false, automation_level: "manual" as const,
    visible_to_client: false, creates_mailing_draft: false, related_feature: "photo-retouching",
  },
  {
    key: "revision",          name: "보정 전달 후 수정 접수",
    order_index: 9,  requires_approval: true,  automation_level: "draft_then_approve" as const,
    visible_to_client: true,  creates_mailing_draft: true,  related_feature: "revision",
  },
  {
    key: "final_delivery",    name: "최종파일 전달 + 후기 요청",
    order_index: 10, requires_approval: true,  automation_level: "draft_then_approve" as const,
    visible_to_client: true,  creates_mailing_draft: true,  related_feature: "mailing",
  },
  {
    key: "review_content",    name: "후기 DB 저장 / 콘텐츠 제작",
    order_index: 11, requires_approval: true,  automation_level: "draft_then_approve" as const,
    visible_to_client: false, creates_mailing_draft: false, related_feature: "review-studio",
  },
  {
    key: "reward",            name: "고객 리워드 (1%)",
    order_index: 12, requires_approval: false, automation_level: "full" as const,
    visible_to_client: false, creates_mailing_draft: false, related_feature: "per",
  },
  {
    key: "customer_care",     name: "고객관리 (주기 알람/이벤트)",
    order_index: 13, requires_approval: true,  automation_level: "draft_then_approve" as const,
    visible_to_client: true,  creates_mailing_draft: true,  related_feature: "mailing",
  },
  {
    key: "content_planning",  name: "스토리 콘텐츠 기획",
    order_index: 14, requires_approval: false, automation_level: "manual" as const,
    visible_to_client: false, creates_mailing_draft: false, related_feature: "content",
  },
];

export const STEP_NAME: Record<string, string> = Object.fromEntries(WORKFLOW_STEPS.map((step) => [step.key, step.name]));

export const MOCK_WORKFLOW_RUNS = [
  {
    id: "run-sample-1",
    client_id: "client-sample-1",
    project_id: "project-sample-1",
    client_name: "운정표병원",
    project_name: "브랜드 촬영 4월",
    current_step_key: "conti_waiting_send",
    current_step_name: "콘티 발송 대기",
    next_action: "콘티 확인 메일 승인 후 발송",
    manager_name: "표진규원장님",
    shoot_date: "2026-04-25",
    status: "active",
    delayed: false,
    waiting_approval_count: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "run-sample-2",
    client_id: "client-sample-2",
    project_id: "project-sample-2",
    client_name: "브라보마취통증의학과",
    project_name: "프리미엄패키지",
    current_step_key: "quote_waiting_send",
    current_step_name: "견적 발송 대기",
    next_action: "견적서 초안 승인",
    manager_name: "김형준원장님",
    shoot_date: "2026-05-17",
    status: "active",
    delayed: true,
    waiting_approval_count: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "run-sample-3",
    client_id: "client-sample-3",
    project_id: "project-sample-3",
    client_name: "라셀의원",
    project_name: "SNS 구독 운영",
    current_step_key: "shoot_reminder",
    current_step_name: "촬영 전 리마인드",
    next_action: "촬영 D-3 리마인드 메일 생성",
    manager_name: "박실장님",
    shoot_date: new Date().toISOString().slice(0, 10),
    status: "active",
    delayed: false,
    waiting_approval_count: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_AGENT_TASKS = [
  {
    id: "task-sample-1",
    title: "운정표병원 갤러리 전달 메일 생성",
    description: "NAS 링크와 대표 썸네일을 포함한 갤러리 전달 메일 초안을 생성합니다.",
    client_name: "운정표병원",
    project_name: "브랜드 촬영 4월",
    workflow_step_key: "gallery_delivery",
    workflow_step_name: "갤러리 전달",
    task_type: "mailing_draft_created",
    priority: "urgent",
    status: "waiting_approval",
    input_data: { nasLink: "NAS 공유 링크", sendTo: "pedpyo1@naver.com" },
    output_data: { subject: "[포토클리닉] 운정표병원 촬영 갤러리 공유" },
    created_at: new Date().toISOString(),
    started_at: null,
    completed_at: null,
  },
  {
    id: "task-sample-2",
    title: "브라보마취통증의학과 견적서 초안 생성",
    description: "프리미엄패키지 기준 견적서 초안을 생성하고 승인 요청합니다.",
    client_name: "브라보마취통증의학과",
    project_name: "프리미엄패키지",
    workflow_step_key: "quote_draft",
    workflow_step_name: "견적서 생성",
    task_type: "quote_draft_created",
    priority: "high",
    status: "pending",
    input_data: { packageName: "프리미엄패키지" },
    output_data: null,
    created_at: new Date().toISOString(),
    started_at: null,
    completed_at: null,
  },
  {
    id: "task-sample-3",
    title: "라셀의원 촬영 D-3 리마인드 생성",
    description: "촬영 전 준비사항과 도착 시간을 포함한 리마인드 초안을 생성합니다.",
    client_name: "라셀의원",
    project_name: "SNS 구독 운영",
    workflow_step_key: "shoot_reminder",
    workflow_step_name: "촬영 전 리마인드",
    task_type: "mailing_draft_created",
    priority: "normal",
    status: "pending",
    input_data: { shootDate: new Date().toISOString().slice(0, 10) },
    output_data: null,
    created_at: new Date().toISOString(),
    started_at: null,
    completed_at: null,
  },
];

export const MOCK_APPROVALS = [
  {
    id: "approval-sample-1",
    title: "운정표병원 갤러리 전달 승인",
    description: "촬영 사진 전달 메일을 병원 담당자에게 발송하기 전 승인해주세요.",
    client_name: "운정표병원",
    project_name: "브랜드 촬영 4월",
    approval_type: "mailing",
    status: "pending",
    related_type: "mailing_queue",
    related_id: "mail-sample-1",
    preview_data: { subject: "[포토클리닉] 운정표병원 촬영 갤러리 공유", button: "갤러리 확인하기" },
    admin_memo: "",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "approval-sample-2",
    title: "브라보마취통증의학과 견적서 초안 승인",
    description: "프리미엄패키지 견적서 금액과 옵션 구성을 확인해주세요.",
    client_name: "브라보마취통증의학과",
    project_name: "프리미엄패키지",
    approval_type: "quote",
    status: "pending",
    related_type: "quote",
    related_id: "quote-sample-1",
    preview_data: { amount: "2,000,000원", packageName: "프리미엄패키지" },
    admin_memo: "",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_LOGS = [
  {
    id: "log-sample-1",
    client_name: "운정표병원",
    project_name: "브랜드 촬영 4월",
    log_type: "approval_requested",
    message: "갤러리 전달 메일 승인 요청이 생성되었습니다.",
    input_summary: "NAS 링크, 담당자 이메일",
    output_summary: "승인 대기함 항목 생성",
    success: true,
    error_message: "",
    created_at: new Date().toISOString(),
  },
  {
    id: "log-sample-2",
    client_name: "브라보마취통증의학과",
    project_name: "프리미엄패키지",
    log_type: "task_created",
    message: "견적서 초안 생성 작업이 큐에 추가되었습니다.",
    input_summary: "프리미엄패키지 상담 메모",
    output_summary: "agent_tasks pending",
    success: true,
    error_message: "",
    created_at: new Date().toISOString(),
  },
];

export const MOCK_TEMPLATE = {
  id: "template-hospital-shoot-basic",
  name: "병원 촬영 기본 워크플로우",
  description: "상담 접수부터 갤러리 전달, 리뷰 요청, PER 포인트 적립까지 이어지는 기본 촬영 운영 플로우입니다.",
  type: "hospital_shoot",
  is_active: true,
  steps: WORKFLOW_STEPS,
};
